### ISSUE TITLE
LLL infinite loop in babai when benchmarking

### ISSUE THREAD

**Issue by WildThingCrypto** [malb/bdd-predicate#19]
I am getting a reduction error in LLL 'infinite loop in babai'.  It seems to be nonces below 200 bit. 

sage -python ecdsa_cli.py benchmark -n 256 -k 160 -m 60 --loglvl DEBUG
:: nlen: 256, m: 60, klen: 160.000, e: 0.00, alg: None, seed: 0x7a6024ad5ea7f89f, params: {}
Traceback (most recent call last):
  File "/root/bdd-predicate/ecdsa_cli.py", line 494, in <module>
    ecdsa()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/bdd-predicate/ecdsa_cli.py", line 117, in benchmark
    run_hnp(
  File "/root/bdd-predicate/ecdsa_hnp.py", line 634, in benchmark
    r = list(map(compute_kernel, J))
  File "/root/bdd-predicate/ecdsa_hnp.py", line 520, in compute_kernel
    key, res = solver(solver=args.algorithm, flavor=args.flavor, **params)
  File "/root/bdd-predicate/ecdsa_hnp.py", line 450, in __call__
    LLL.Reduction(self.M)()
  File "src/fpylll/fplll/lll.pyx", line 305, in fpylll.fplll.lll.LLLReduction.__call__
fpylll.util.ReductionError: b'infinite loop in babai'

**Comment by malb** [comment]
I can reproduce this, this diff seems to fix it.

```diff
diff --git a/ecdsa_hnp.py b/ecdsa_hnp.py
index bff3531..7275aa1 100644
--- a/ecdsa_hnp.py
+++ b/ecdsa_hnp.py
@@ -263,7 +263,8 @@ class ECDSASolver(object):
                 A,
                 U=IntegerMatrix.identity(A.nrows, int_type=A.int_type),
                 UinvT=IntegerMatrix.identity(A.nrows, int_type=A.int_type),
-                flags=GSO.ROW_EXPO,
+                float_type="dd",
+                # flags=GSO.ROW_EXPO,
             )
         M.update_gso()
         return M
```

**Comment by WildThingCrypto** [comment]
Thank you. Is their a benefit of using "dd" specifically in the smaller fields?
